### ISSUE TITLE
C# Specflow definition goto navigates to step embedded within another step

### ISSUE THREAD

**Issue by gdstirling** [alexkrechik/VSCucumberAutoComplete#215]
**Describe the bug**
In C# specflow, it is possible to call a step within another step (see `.cs` example below). This seems to get in the way of the extensions ability to navigate to a definition.

**To Reproduce**
1. Select a step that happens to be embedded within another step
2. Go to definition
3. Navigates to an embedded use of the step within .cs file.

**Expected behavior**
Navigate to the actual definition, not the use of it embedded within a high level step.

**Gherkin step line**
example.feature

```
  Scenario: This is an example step
    Given calls an embedded step    # goto definition does not navigate to the steps def
```

**Step definition:**
Example of step definition:
steps.cs
```
        [StepDefinition(@"calls an embedded step")]
        public void AnotherStep()
        {
                Log.Info("This is another step");
        }

        [StepDefinition(@"high level step")]
        public void HighLevelStep()
        {
                Log.Info("Call another step");
                And("calls an embedded step");    // <- Plugin navigates to this step
        }
```

**Comment by alexkrechik** [comment]
Unfortunately, actually extension looking for all the steps-like string and using the last one with current step. Add an ability of some additional logic would be possible only after full steps detection rewrite, which, actually, is without some ETA.

**Comment by mtkennerly** [comment]
@alexkrechik Wouldn't it be possible, without a full rewrite, to add an option like `cucumberautocomplete.stepDefinitionInclude` that you could set to regexes of lines that should be considered? I would think you could keep the existing logic, but first just filter the list of possibilities from all lines to only those lines matched by the patterns. For example, using Python and Behave, we could set this to `["^@(given|when|then|step)\("]`.

Just to add an extra data point, I ran into this issue with Python/Behave, but it only happens if the embed line has quotes (I guess because of the regex that the plugin is using). So both of these will jump you to the correct definition:

```python
from behave import *

@given("an embedded step")
def step_impl(context):
    pass

@given("an outer step")
def step_impl(context):
    context.execute_steps("""
        Given an embedded step
    """)
```

```python
from behave import *

@given("an outer step")
def step_impl(context):
    context.execute_steps("""
        Given an embedded step
    """)

@given("an embedded step")
def step_impl(context):
    pass
```

...while this one takes you to the wrong location:

```python
from behave import *

@given("an outer step")
def step_impl(context):
    context.execute_steps("""
        Given an "embedded" step
    """)

@given('an "embedded" step')
def step_impl(context):
    pass
```

.vscode/settings.json:
```json
{
    "cucumberautocomplete.steps": ["steps/*.py"],
    "cucumberautocomplete.strictGherkinCompletion": false
}
```

**Comment by alexkrechik** [comment]
Should be supported in 2.13.0
