### ISSUE TITLE
autoformat with unicode characters

### ISSUE THREAD

**Issue by tbhi** [alexkrechik/VSCucumberAutoComplete#259]
Running autoformat with the following does not correctly format as shown:
```
    Examples:
      | language |
      | हिंदी    |
```

**Comment by alexkrechik** [comment]
Unfortunately, was unable to fix this issue - please look at the screens. Correct num of characters was provided to the VSCode, but, due to some reason, editor doesn't display two spaces:
<img width="211" alt="Screen Shot 2019-04-14 at 5 14 26 PM" src="https://user-images.githubusercontent.com/5772406/56094098-f0f44d00-5ed8-11e9-8b8e-4b6990345dd1.png">
<img width="275" alt="Screen Shot 2019-04-14 at 5 14 18 PM" src="https://user-images.githubusercontent.com/5772406/56094099-f0f44d00-5ed8-11e9-8dfa-617593a614e2.png">

**Comment by alexkrechik** [comment]
Looks like, that we can fix this issue for some fonts - see https://github.com/alexkrechik/VSCucumberAutoComplete/pull/278

**Comment by joeky888** [comment]
```js
console.log("हिंदी".length) // 5
``` 

You'll need to use a font that makes the word `हिंदी` equals to 5 English letters length.

**Comment by SylChamber** [comment]
I have the same problem with French. Notice the curved quote in the third line. I'm using the default Windows VSCode font, `Consolas`.

```
| date         |
| aujourd'hui  |
| aujourd’hui |
| hier         |
| mañana       |
```

The curved quote is "right single quotation mark", U+2019 in the [General Punctuation Unicode block](https://en.wikipedia.org/wiki/General_Punctuation) (and produced with the Canadian Multilingual keyboard with `shift+right ctrl+B`). That's the only character I use in my features that is not in the [Basic Latin](https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)) or [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)) Unicode blocks.

I use this character because SpecFlow (.NET Cucumber implementation) works correctly only if parameters are enclosed in quotes: ` '<parameter>' `. Which causes no end of trouble for French speakers since the quote is largely used. My trick is to always use the "right single quotation mark" in feature text instead of the single quote.

Is it possible that format does not work with characters that are in the range > x0100 ?

What is curious, is that if I assign "`aujourd'hui`" and "`aujourd’hui`" to variables and ask for their `.length` in a Node.js terminal or a browser console, they both have the same length, no need to normalize.

**Comment by joeky888** [comment]
I guess it is nessecarily to consider a non-ascii character to be 2 ascii character length.

```js
[..."हिंदी"].reduce((a, b) => a + (/^[\u0000-\u007f]*$/.test(b) ? 1:2), 0) // 10

[..."aujourd'hui"].reduce((a, b) => a + (/^[\u0000-\u007f]*$/.test(b) ? 1:2), 0) // 11
[..."aujourd’hui"].reduce((a, b) => a + (/^[\u0000-\u007f]*$/.test(b) ? 1:2), 0) // 12
```

**Comment by bolatbekb** [comment]
I have the same problem with Cyrillic.

http://joxi.ru/xAeygYyCRx060A
