### ISSUE TITLE
Support for general defined objects

### ISSUE THREAD

**Issue by ri0ter** [alexkrechik/VSCucumberAutoComplete#33]
Right now in config I can only define objects in the context of some page using `cucumberautocomplete.pages`.
I'm missing support for objects defined in general, the ones that are not tight to some particular page to use it like this: `When I click "alarm button"`.

**Comment by alexkrechik** [comment]
Could you please give me more info about general objects with examples? 
Where "alarm button" from your example defined?

**Comment by ri0ter** [comment]
Well we have lib/components.js file where all components are defined and inside there's are key value pairs that we use inside features. 
Just aside note I'm new to cucumber so I might be doing it wrong but to be hones it seems semantically better to use a name defined inside one quote than combining quoted objects.

**Comment by alexkrechik** [comment]
Unfortunately, changing of pages object to using of key => value pairs from some single file appears to be dirty hack in our case. In future releases I'm planning to add some other page objects separator supports (ex. "page object" instead of "page"."object"), but each page should be related to some file, which contains some variables-like values
