### ISSUE TITLE
Was unable to find step

### ISSUE THREAD

**Issue by Arelav** [alexkrechik/VSCucumberAutoComplete#393]
**Describe the bug**
Was unable to find step when implementation is arrow function without curly braces (implicit return)

**To Reproduce**
Create the feature for example
```
Feature: Test feature

  Scenario: Test scenario
    Given the test cookie is set
```
Make an implementation (we use `"tests/support/step_definitions/**/*.ts"`)
```typescript
Given('the test cookie is set', () => cy.setCookie('TEST_COOKIE', 'true'));
```    

**Expected behavior**
It should find the implementation
I noticed it will work when it's
```
Given('the test cookie is set', () => {
  cy.setCookie('TEST_COOKIE', 'true');
});
```
however implicit return function is also valid implementation.
**Screenshots**
Implicit return:
![image](https://user-images.githubusercontent.com/1059539/117510177-9adc2180-af59-11eb-8513-af39b281b9e6.png)
Curly:
![image](https://user-images.githubusercontent.com/1059539/117510161-931c7d00-af59-11eb-8f57-24f0f8c17270.png)

**Cucumberautocomplete part of VSCode settings:**
```
{
  "cucumberautocomplete.onTypeFormat": true,
  "cucumberautocomplete.smartSnippets": true,
  "cucumberautocomplete.strictGherkinCompletion": true,
  "cucumberautocomplete.steps": [
    "tests/support/step_definitions/**/*.ts",
  ],
  "cucumberautocomplete.customParameters": [
    {
      "parameter": "{string}",
      "value": ".*"
    }
  ]
}
```

**Step definition:**
If applicable, add example of step definition:
```
Given('the test cookie is set', () => cy.setCookie('TEST_COOKIE', 'true'));
```

**Gherkin step line**
```
Given the test cookie is set
```

**Comment by Arelav** [comment]
Is this project doesn't have a maintainer anymore? I wouldn't expect a fix but at least to have some response would be nice.

**Comment by alexkrechik** [comment]
Yes, sorry for the long response. I'm thinking regarding some ability to use such steps - maybe this would be some additional  option or some regex setting recomendation.

**Comment by stevenlafl** [comment]
I also use arrow functions and this is problematic for me as well. +1

**Comment by rioj7** [comment]
A more readable regex would be

```
When(/^I should (not )?see (?:the )?"([^"]*)" link$/, (visible, text) => {
    shouldSeeLink(text, visible.length === 0);
});
```

**Comment by Bill77** [comment]
So I debugged the server code and discovered, that the parser is parsing line by line. When it tries to get the step information, it's using the last `'` in the line as the delimiter to determine the step information. The reason in-line arrow functions are not working is because when it parses:

`Given('the test cookie is set', () => cy.setCookie('TEST_COOKIE', 'true'));` 

The parser believes the step rule is:

`'the test cookie is set', () => cy.setCookie('TEST_COOKIE', 'true'` 

Instead of:

`'the test cookie is set'`

> Obviously, when you use `{}` around a function, prettier or other formatters, add the new line, thus the line-by-line parsing continues to work.

So what happens is when that string is used to [create a regular expression object, it errors](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/bc8d2ba15870b5ff84d5c9cf042097d32919e0af/gserver/src/steps.handler.ts#L381) and the step definition is not added, thus we get the warning in the editor view.

**The solution would be to update the regular expression to not assume the last `'` or `"` is the end of the string (I think - the current regex is pretty hairy).**

---

As a workaround (thankfully in our case we have only a few variants) you can modify the `cucumberautocomplete.customParameters` to replace the in-line strings so the parser can work correctly.

```json
...
"cucumberautocomplete.customParameters": [
    { "parameter": "'TEST_COOKIE", "value": "" },
    { "parameter": "'true'", "value": "" }
  ],
...
```

> At least that solution seems to work for us. 😄

**Comment by navinrrsingh** [comment]
Hi @alexkrechik - Would you be review changes by @Bill77

**Comment by alexkrechik** [comment]
Yeah, reviewed and added some comments.
